// <auto-generated />
using CodeFirstEFWithFluentApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstEFWithFluentApi.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("CodeFirstEFWithFluentApi.Model.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnName("the actor of this book")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnName("the description of this book")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("the title of this book")
                        .HasColumnType("TEXT");

                    b.HasKey("ID")
                        .HasName("#");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
